# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
theme = "congo"
defaultContentLanguage = "ru"
baseURL = "https://your_domain.com/"
languageCode = "ru"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

timeout = "90s"

[outputs]
  home = ["HTML", "RSS", "JSON"]
