# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "О кафедре"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Образование"
  pageRef = "education"
  weight = 2

[[main]]
  name = "Наука"
  pageRef = "science"
  weight = 3

# [[main]]
#   name = "Услуги"
#   pageRef = "services"
#   weight = 4

[[main]]
  name = "Новости"
  pageRef = "news"
  weight = 5

# [[main]]
#   name = "Блог"
#   pageRef = "blog"
#   weight = 6

[[main]]
  name = "Контакты"
  pageRef = "contacts"
  weight = 7


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "О кафедре"
  pageRef = "about"
  weight = 1

[[footer]]
  name = "Образование"
  pageRef = "education"
  weight = 2

[[footer]]
  name = "Наука"
  pageRef = "science"
  weight = 3

# [[footer]]
#   name = "Услуги"
#   pageRef = "services"
#   weight = 4

# [[footer]]
#   name = "Новости"
#   pageRef = "news"
#   weight = 5

# [[footer]]
#   name = "Блог"
#   pageRef = "blog"
#   weight = 6

[[footer]]
  name = "Контакты"
  pageRef = "contacts"
  weight = 7

