[build]
  command = "hugo --gc --minify -b $URL"
  publish = "site"
  
[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "UTC+3"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.100.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.100.2"
