backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: img
collections:
  - name: 'stuff'
    label: 'Сотрудники'
    folder: 'content/about/stuff'
    create: false
    editor:
      preview: false
    fields:
      - label: 'Имя сотрудника'
        name: 'title'
        widget: 'string'
        hint: Имя Отчество Фамилия
      - label: "Лаборатория"
        name: "branch"
        widget: "select"
        options:
          - Лаборатория аэрокосмических методов
          - Лаборатория автоматизации в картографии
          - Лаборатория цифровой картографии и фотограмметрии
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        hint: '{{< lead >}} Должность {{< /lead >}} \n [Страница в Истине](url) \n ![Фотокарточка](url Подпись)'